name: Deploy to Koyeb

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'

            - name: Build JAR file
              run: |
                  chmod +x gradlew
                  ./gradlew clean bootJar

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                  docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/advshop-app:latest .
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/advshop-app:latest

            - name: Deploy to Koyeb
              run: |
                  curl -X POST "https://app.koyeb.com/v1/apps/${{ secrets.KOYEB_APP_ID }}/deployments" \
                    -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
                    -H "Content-Type: application/json" \
                    --data '{"strategy":"ROLLING"}'
